export const actionType = {
    ADD_TO_BASKET: 'ADD_TO_BASKET',
    TOGGLE_TODO: 'TOGGLE_TODO',
    REMOVE_FROM_BASKET: 'REMOVE_FROM_BASKET',
    SET_SHOW_BASKET: 'SET_SHOW_BASKET',
    CLEAR_BASKET: 'CLEAR_BASKET',
    INCREASE_QTY: 'INCREASE_QTY',
    DECREASE_QTY:'DECREASE_QTY'
}